---
openapi: 3.0.0
info:
  description: Practice API for System Commands
  version: 1.0.0-oas3
  title: Practice API for System Commands
  contact:
    email: marshall@theonsruds.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:

  "/uptime":
    get:
      summary: Get the uptime for the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uptime:
                    type: string

  "/date":
    get:
      summary: Get the date from the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string

  "/uname":
    get:
      summary: Get the uname from the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uname:
                    type: string                    

  "/memory":
    get:
      summary: Get the memory utilization for the system in kB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_memory:
                    type: integer
                  used_memory:
                    type: integer
                  free_memory:
                    type: integer
  "/df":
    get:
      summary: Get the disk utilization for the system
      responses:
        '200':
          description: An array of objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    device:
                      type: string
                    space_used:
                      type: integer
                    space_available:
                      type: integer
                    percent_used:
                      type: string

  "/cpu":
    get:
      summary: Get the cpu information for the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  model_name:
                    type: string
                  cpu_mhz:
                    type: float
                  cpu_cores:
                    type: integer


servers:
- url: http://127.0.0.1:8080/monitor/1.0.0

